[versions]
androidJunit5 = "1.13.4.0"
androidPdfview = "3.2.14"
androidTest = "1.9.0"
checkerFramework = "3.52.0"
ddPlist = "1.28"
espresso = "3.7.0"
exoplayer = "2.19.1"
firebaseMessagingKtx = "24.1.2"
googleServices = "4.4.4"
gravitySnapHelper = "2.2.2"
gsSdk = "5.13.0"
junitJupiter = "5.13.4"
kotlinFaker = "1.16.0"
lifecycleProcess = "2.10.0"
materialDateTimePicker = "4.2.3"
mockWebServer = "5.3.2"
pahoMqttAndroid = "4.4.1"
realmAndroidAdapters = "v4.0.0"
realmGradlePlugin = "10.19.0"
touchImageView = "3.7.1"
uiAndroid = "1.10.0"
uiAutomator = "2.3.0"
viewpager2 = "1.1.0"
webkit = "1.14.0"

[libraries]
android-junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "androidJunit5" }
android-pdfview = { module = "com.github.Infomaniak:android-pdfview", version.ref = "androidPdfview" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "uiAndroid" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
dd-plist = { module = "com.googlecode.plist:dd-plist", version.ref = "ddPlist" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
extension-okhttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "exoplayer" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gravity-snap-helper = { module = "com.github.rubensousa:gravitysnaphelper", version.ref = "gravitySnapHelper" }
gs-sdk = { module = "com.geniusscansdk:gssdk", version.ref = "gsSdk" }
infomaniak-core = { module = "com.infomaniak.core:Common" }
infomaniak-core-auth = { module = "com.infomaniak.core:Auth" }
infomaniak-core-avatar = { module = "com.infomaniak.core:Avatar" }
infomaniak-core-coil = { module = "com.infomaniak.core:Coil" }
infomaniak-core-crossapplogin = { module = "com.infomaniak.core:CrossAppLogin.Front" }
infomaniak-core-fragmentnavigation = { module = "com.infomaniak.core:FragmentNavigation" }
infomaniak-core-inappreview = { module = "com.infomaniak.core:InAppReview" }
infomaniak-core-inappupdate = { module = "com.infomaniak.core:InAppUpdate" }
infomaniak-core-ksuite = { module = "com.infomaniak.core:KSuite" }
infomaniak-core-ksuite-pro = { module = "com.infomaniak.core:KSuite.KSuitePro" }
infomaniak-core-ksuite-myksuite = { module = "com.infomaniak.core:KSuite.MyKSuite" }
infomaniak-core-ktor = { module = "com.infomaniak.core:Ktor" }
infomaniak-core-matomo = { module = "com.infomaniak.core:Matomo" }
infomaniak-core-network = { module = "com.infomaniak.core:Network" }
infomaniak-core-recyclerview = { module = "com.infomaniak.core:RecyclerView" }
infomaniak-core-sentry = { module = "com.infomaniak.core:Sentry" }
infomaniak-core-thumbnails = { module = "com.infomaniak.core:Thumbnails" }
infomaniak-core-twofactorauth-back = { module = "com.infomaniak.core:TwoFactorAuth.Back.WithUserDb" }
infomaniak-core-twofactorauth-front = { module = "com.infomaniak.core:TwoFactorAuth.Front" }
infomaniak-core-ui = { module = "com.infomaniak.core:Ui" }
infomaniak-core-ui-compose-basics = { module = "com.infomaniak.core:Ui.Compose.Basics" }
infomaniak-core-ui-compose-margin = { module = "com.infomaniak.core:Ui.Compose.Margin" }
infomaniak-core-ui-compose-materialthemefromxml = { module = "com.infomaniak.core:Ui.Compose.MaterialThemeFromXml" }
infomaniak-core-ui-view-edgetoedge = { module = "com.infomaniak.core:Ui.View.EdgeToEdge" }
kotlin-faker = { module = "io.github.serpro69:kotlin-faker", version.ref = "kotlinFaker" }
material-date-time-picker = { module = "com.wdullaer:materialdatetimepicker", version.ref = "materialDateTimePicker" }
mock-web-server = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }
paho-mqtt-android = { module = "com.github.hannesa2:paho.mqtt.android", version.ref = "pahoMqttAndroid" }
realm-android-adapters = { module = "com.github.realm:realm-android-adapters", version.ref = "realmAndroidAdapters" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realmGradlePlugin" }
touch-image-view = { module = "com.github.MikeOrtiz:TouchImageView", version.ref = "touchImageView" }

# Unit tests
android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidTest" }
android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidTest" }
androidx-espresso-checker = { module = "org.checkerframework:checker", version.ref = "checkerFramework" } # Not unused, don't remove it
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-ui-automator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }

[plugins]
junit5 = { id = "de.mannodermaus.android-junit5" }
kotlin-android = { id = "kotlin-android" }
kotlin-kapt = { id = "kotlin-kapt" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin" }
realm-android = { id = "realm-android" }
